# Generated by Django 3.2.20 on 2023-07-31 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=200)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2023, 7, 31, 19, 47, 41, 422207), editable=False)),
            ],
        ),
    ]
