# Generated by Django 3.2.20 on 2023-07-31 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 19, 48, 25, 834812), editable=False),
        ),
    ]
