# Generated by Django 3.2.20 on 2023-07-31 20:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_accesstoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 20, 44, 35, 3673, tzinfo=utc), editable=False),
        ),
    ]
