# Generated by Django 3.2.20 on 2023-07-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_accesstoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
